version: "3"
services:
  nginx:
    container_name: nginx
    image: inception/nginx:1.0
    ports:
      - 443:443
    networks:
      - frontend
      - backend
    restart:
      on-failure
  wordpress:
    container_name: wordpress
    image: inception/wordpress:1.0
    depends_on:
      - maria_db
    ports:
     - 443:443
    networks:
      - backend
      - backend2
    volumes:
      - /var/container/CDN:/var/www/html
    restart:
      on-failure
  maria_db:
    image: inception/maria_db:1.0
    networks:
      - backend2
    environment:
      - WP_DB_NAME=${WP_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      -/var/container/DB:/var/lib/mysql
networks:
  frontend:
    driver: bridge
  backend:
    external: false
  backend2:
    external: false
  volumes:
    mariadb-volume:
      driver: local
      driver_opts:
        type: none
        device: ${DB_VOL_PATH}
        o: bind
    wordpress-volume:
      driver: local
      driver_opts:
        type: none
        device: ${WP_VOL_PATH}
        o: bind