version: "3"


services:
#########################
########  Nginx  ########
#########################
  nginx:
    container_name: nginx
    image: inception/nginx:1.0
    ports:
      - 443:443
    networks:
      - frontend
      - backend
    volumes:
      - wordpress-volume:/var/www/html
    restart:
      on-failure

##########################
######  Wordpress  #######
##########################
  wordpress:
    container_name: wordpress
    image: inception/wordpress:1.0
    depends_on:
      - maria_db
    expose:
     - "9000"
    networks:
      - backend
      - backend2
    volumes:
      - wordpress-volume:/var/www/html
    restart:
      on-failure
#########################
#######  MariaDB  #######
#########################
  maria_db:
    container_name: mariadb
    image: inception/mariadb:1.0
    expose:
     - "3306"
    networks:
      - backend2
    environment:
      - WP_DB_NAME=${WP_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - mariadb-volume:/var/lib/mysql

##########################
#######  Networks  #######
##########################
networks:
  frontend:
    driver: bridge
  backend:
    external: false
  backend2:
    external: false

########################
#######  Volumes #######
########################
volumes:
    mariadb-volume:
      driver: local
      driver_opts:
        type: none
        device: ${DB_VOL_PATH}
        o: bind
    wordpress-volume:
      driver: local
      driver_opts:
        type: none
        device: ${WP_VOL_PATH}
        o: bind