version: "3"


services:
#########################
########  Nginx  ########
#########################
  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: inception/nginx:1.0
    depends_on:
      - wordpress
    ports:
      - 443:443
    networks:
      - frontend
      - backend
    volumes:
      - wordpress-volume:/var/www/html
    restart:
      on-failure

##########################
######  Wordpress  #######
##########################
  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    image: inception/wordpress:1.0
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - backend
      - backend2
    volumes:
      - wordpress-volume:/var/www/html
    restart:
      on-failure

#########################
#######  MariaDB  #######
#########################
  mariadb:
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    image: inception/mariadb:1.0
    networks:
      - backend2
    env_file:
      - .env
    volumes:
      - mariadb-volume:/var/lib/mysql

##########################
#######  Networks  #######
##########################
networks:
  frontend:
    driver: bridge
  backend:
    external: false
  backend2:
    external: false

########################
#######  Volumes #######
########################
volumes:
    mariadb-volume:
      driver: local
      driver_opts:
        type: none
        device: ${DB_VOL_PATH}
        o: bind
    wordpress-volume:
      driver: local
      driver_opts:
        type: none
        device: ${WP_VOL_PATH}
        o: bind